[ui]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[theme]
primaryColor       = "#00D09C"
backgroundColor    = "#F4F4F9"
secondaryBackgroundColor = "#FFFFFF"
textColor          = "#1A2236"
font               = "sans serif"
